### ISSUE TITLE
Kemono.su Load related links bug

### ISSUE THREAD

**Issue by joeywen0830** [NC22/KellyC-Image-Downloader#11]
I'm using the newest version of stable chrome. On kemono.su, the extension always show "can't load or timeout reached" error when using the Load related links feature.

**Comment by NC22** [comment]
@joeywen0830 Hi. You can leave additional info to radiokellyc@gmail.com or give an SFW example here. 

Is it always fail to load from related links ? Is VPN used ? Is host - https://img.kemono.su/ not blocked by your provider ? (if you go directly to https://img.kemono.su/ it should show "OK") 

Extension cant load data from related link in some cases - for ex. reached requsts limit by VPN \ banned from site itself. I discribed some ways to solve here https://kellydownloader.com/en/links/loadrelated/ but work with VPN can be tricky and depends on quality of VPN itself.

Currently I dont see any problems with work on kemono, filter it self not deprecated and works correctly. I tested on some random pages without any proxy.

**Comment by NC22** [comment]
This problem can be related to some specifed host name. On your screenshot is not img.kemono.su host is used - c2 \ c4 is used in your case - for my location kemono is not return any similar hosts, so I cant check access \ possible issues. Also its unsual related document links - in usuall usecase if you open an artist page -> then click "Record" -> post related links will contain url parts linke "/post/740675" so on screenshot is not links to related publications.
