### ISSUE TITLE
Скачивающиеся картинки не открываются в просмотрщике

### ISSUE THREAD

**Issue by burivuh26** [NC22/KellyC-Image-Downloader#12]
Окружение:
macbook pro 14 m1pro
macos 14.2.1
Chrome Stable последний (122.0.6261.112)

проверенные сайты: devianart, artuntamed, e-hentai. 
Во всех случаях всё штатно до момента скачивания картинок на компьютер. Они выкачиваются в вкладку расширения, если скачать список ссылок и открыть какую-то из них, то изображение будет в браузере. Но после загрузки, изображения не открываются в просмотрщике, возможно они подвреждены.

Прикрепляю архив с логами. 
[Архив.zip](https://github.com/NC22/KellyC-Image-Downloader/files/14549651/default.zip)

**Comment by NC22** [comment]
@burivuh26 Привет. Ошибка по логам не отслеживается, возможно есть какие-то разночтения на уровне api сохранения изображений конкретно под маком, но проверить нет возможности. Версия браузера та же. 

В настройках можно попробовать поменять метод сохранения, это может помочь если есть проблемы с передачей бинарных данных в фоновый процесс расширения, но в новых версиях хрома эта проблема уже давно не встречалась.

![35](https://github.com/NC22/KellyC-Image-Downloader/assets/1849073/01a9716a-b69d-40c4-9bb7-07d62838524c)

если не поможет надо смотреть что пишет в сами файлы. можешь для теста скинуть какой-нибудь неоткрываемый sfw файл или с DA или например с https://catface.ru/ если там проблема тоже есть.

**Comment by burivuh26** [comment]
Спасибо. 
У меня в macos нет другого способа передачи данных в фоновый процесс, но изменение способа скачивания на Fetch мне помогло.
