### ISSUE TITLE
Это больше не работает ?

### ISSUE THREAD

**Issue by Toshik-One** [NC22/KellyC-Image-Downloader#16]
Сейчас заметил  на joyreactor   перестало работать функция  "Снятие блокировок"  постоянно и в любом случае выдаёт "Реактор вернул все еще зацензуренный пост. Попробуйте временно использовать функцию просмотра тега напрямую в шапке  [#]"

**Comment by NC22** [comment]
ага. с месяц назад был тред https://joyreactor.cc/post/5887201 мб чего полезного там найдешь
