### ISSUE TITLE
[BUG] - deviantart (Original Image doesn't work)

### ISSUE THREAD

**Issue by FloxY-Y** [NC22/KellyC-Image-Downloader#5]
A screenshot of what happens when I try to look at the original image :
![ScreenShot](https://user-images.githubusercontent.com/47297859/174435190-dc6358fb-6fef-4860-ae19-7e42f7527d44.png)

**Comment by NC22** [comment]
Thanks for notification. They update routing, so need to add some changes in filters. I'll notify when extension will be updated

**Comment by FloxY-Y** [comment]
Thank you i didn't think you would see my issue so quickly

**Comment by NC22** [comment]
added fixes in 1.2.2.7 ver.

**Comment by FloxY-Y** [comment]
Thank
