### ISSUE TITLE
Deviantart - downloadable originals

### ISSUE THREAD

**Issue by LostInTheShell** [NC22/KellyC-Image-Downloader#6]
Hi.

When starting from a search, like:
https://www.deviantart.com/search/deviations?q=midjourney

if an image in the results has a downloadable original, like this image:
https://www.deviantart.com/einlion0/art/Made-in-Abyss-926593180

the original, present in the "download" link, doesn't show up in the "load related links" process, only the reduced "original"
So, in the example above, starting from the search and loading related links we only see 894x894 picture, and no the 1024x1024 linked underneath

**Comment by NC22** [comment]
@LostInTheShell thanks. updated. Check when version 1.2.3.7 will be approved by chrome \ ff extension stores moderation (usually from 1-7 days)
