### ISSUE TITLE
Joyreactor, невозможно оставить оценку или комментарий на разблокированном посте

### ISSUE THREAD

**Issue by tipoima** [NC22/KellyC-Image-Downloader#9]
![image](https://github.com/NC22/KellyC-Image-Downloader/assets/61978315/09b03e3b-f1c0-4a1a-8be2-7708dfd00da9)

**Comment by NC22** [comment]
спс. в версии 1.2.7.8 добавил поддержку отправки комментов через api на пробу, вроде работает. Именно с +\- пока проблему не заметил - они работают нативно через скрипты самого реактора, но мб есть исключения, там где ставил +\- срабатывало штатно. В общем пока в тестовом режиме, мб чего забыл, но в ближайшие дни детально проверить возможности скорее всего не будет.

версия в FF уже доступна, в хроме и пр. на проверке модерации до 2-7 дней

**Comment by tipoima** [comment]
Обновился до 1.2.7.8, однако печаль
![image](https://github.com/NC22/KellyC-Image-Downloader/assets/61978315/df1c03df-6a3c-477e-8211-d7bad2146a0d)
Chrome 118.0.5993.89

**Comment by NC22** [comment]
Ага, тоже гляну, видимо есть разночтения с отдельными постами в ленте тк успел глянуть только заблоченые посты в режиме открытия всего тега (через кнопку [#] в шапке с кнопками насширения)

**Comment by NC22** [comment]
добавлен фикс в v1.2.7.9

**Comment by tipoima** [comment]
Приключение продолжается.
Комменты на другие комменты отправляются как коммент на пост.

**Comment by NC22** [comment]
спасибо, учел в 1.2.8.0. там форму заново реализовывать под новое апи приходится, потому такие базовые моменты и всплывают, а потестить все сценарии как и сказал пока было некогда. Так что если еще чего будет пиши. С вложениями \ из файла, тоже вроде отправляет и так и так сейчас, но мб чего еще осталось. Сам перепроверю наверное уже ближе к концу недели.
